# "제로부터 시작하는 러스트 백엔드 프로그래밍" 연습용 프로젝트
[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"
authors = ["aquatic"]

[lib]
# 어떤 형태의 경로든 기술할 수 있지만 커뮤니티의 관습을 따른다.
# `name` 필드를 사용해서 라이브러리 이름을 지정한다.
# 지정하지 않으면 cargo는 `package.name`을 사용한다.
path = "src/lib.rs"
