[package]
name = "zero2prod_axum"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
# 웹 프레임워크
axum = { version = "0.8", features = ["form"] }
# 시간
chrono = "0.4"
# 설정
config = "0.15"
log = "0.4"
# 마킹
secrecy = { version = "0.10", features = ["serde"] }
# 직렬화
serde = { version = "1", features = ["derive"] }
# Postgres
sqlx = { version = "0.9", features = ["chrono", "postgres", "runtime-tokio", "tls-rustls", "uuid"] }
thiserror = "2"
# 비동기 처리
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tower = "0.5"
# axum 미들웨어
tower-http = { version = "0.6", features = ["trace"] }
# 로그
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
unicode-segmentation = "1"
# swagger
utoipa = { version = "5", features = ["axum_extras"] }
utoipa-axum = "0.2"
utoipa-swagger-ui = { version = "9", features = ["axum"] }
# uuid
uuid = { version = "1", features = ["v4"] }
# 이메일 유효성 검증
validator = "0.20"

[dev-dependencies]
# 무작위 데이터 생성
fake = "5"
# 속성 테스트
quickcheck = "1"
quickcheck_macros = "1"
# http 요청
reqwest = "0.13"
# axum에 각종 편의 기능 추가
tower = { version = "0.5", features = ["util"] }
