[package]
name = "zero2prod_axum"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod_axum"

[workspace]
members = [".", "migration"]

[dependencies]
axum = { version = "0.8", features = ["macros"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
config = "0.15"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
sea-orm = { version = "1.1", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
] }
secrecy = { version = "0.10", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde-aux = "4.7"
tokio = { version = "1.47", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6", features = ["trace"] }
tracing = { version = "0.1", features = ["log"] }
tracing-log = "0.2"
tracing-subscriber = { version = "0.3", features = [
    "registry",
    "env-filter",
    "json",
] }
unicode-segmentation = "1.12"
uuid = { version = "1.17", features = ["v4"] }
validator = "0.20"

[dev-dependencies]
migration = { path = "./migration" }
claim = "0.5"
fake = "4.4"
quickcheck = "1.0"
quickcheck_macros = "1.1"
wiremock = "0.6"
serde_json = "1.0"
