[package]
name = "zero2prod_axum"
version = "0.1.0"
edition = "2021"
authors = ["aquatic"]
description = "'제로부터 시작하는 러스트 백엔드 프로그래밍' 연습용 프로젝트. actix-web 대신 axum을 사용했다."

[lib]
# 어떤 형태의 경로든 기술할 수 있지만 커뮤니티의 관습을 따른다.
# `name` 필드를 사용해서 라이브러리 이름을 지정한다.
# 지정하지 않으면 cargo는 `package.name`을 사용한다.
path = "src/lib.rs"

# 이중 대괄호는 TOML에서의 배열 표기 문법이다.
# 프로젝트에 하나의 라이브러리는 물론 여러 바이너리를 포함할 수도 있다.
[[bin]]
path = "src/main.rs"
name = "zero2prod_axum"

[dependencies]
axum = { version = "0.7", features = ["http2"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
