# production 테스트를 위한 docker-compose
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=newsletter
  zero2prod_axum:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      # 환경에 맞춰서 수정해야 한다.
      - APP_ENVIRONMENT=production
      - APP_APPLICATION__HMAC_SECRET=wXkuBascKVdODkarGs/fE1PG/4SoFIR56PZIwnOlbC1/NlXd6JDzTpG9h4vwDeFmvVpgl0iUf/t4MqAh/eX9+g
      - APP_APPLICATION__BASE_URL=http:://127.0.0.1
      - APP_DATABASE__HOST=postgres
      - APP_DATABASE__PORT=5432
      - APP_DATABASE__USERNAME=postgres
      - APP_DATABASE__PASSWORD=password
      - APP_DATABASE__DATABASE_NAME=newsletter
      - APP_DATABASE__REQUIRE_SSL=false
      - APP_EMAILCLIENT__BASE_URL=http://127.0.0.1
      - APP_EMAILCLIENT__SENDER_EMAIL=sender@localhost
      - APP_EMAILCLIENT__AUTHORIZATION_TOKEN=mytoken
      - APP_EMAILCLIENT__TIMEOUT_MILLISECONDS=10000
