[package]
name = "pm_mock_server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
claim = "0.5.0"
http = "1.3.1"
http-serde = "2.1.1"
reqwest = { version = "0.12.15", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.2" }
zero2prod_axum = { version = "0.1", path = "../" }
