application_port: 8000
database:
  username: postgres
  password: password
  database_name: newsletter
  host: localhost
  port: 5432
application:
  base_url: "http://127.0.0.1"
  port: 8000
  token_secret_private_pem: "private.pem"
  token_secret_public_pem: "public.pem"
email_client:
  base_url: "localhost"
  sender_email: "test@example.com"
  authorization_token: "change-me"
  timeout_milliseconds: 10000
