application_port: 8000
database:
  username: postgres
  password: password
  database_name: newsletter
  host: localhost
  port: 5432
  token_secret: "long-and-very-secret-random-key-needed-for-authentication"
application:
  base_url: "http://127.0.0.1"
  port: 8000
email_client:
  base_url: "localhost"
  sender_email: "test@example.com"
  authorization_token: "change-me"
  timeout_milliseconds: 10000
